name = "NoLongerProblems_Pandas"
uuid = "5d29c26c-ce79-4baf-a522-6e725d77eda7"
authors = ["Irene Robles Rebollo <irenerobles93@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
